### ISSUE TITLE
"meta: reset_connection" doesn't work with vagrant driver

### ISSUE THREAD

**Issue by tdewitt** [ansible-community/molecule-vagrant#1]
### Description
When using the vagrant driver, `meta: reset_connection` does not work as expected.  The expectation is that the connection to the VM will be reset and ansible we reconnect and continue processing tasks.  This is commonly used when making user modifications (like group membership) that are needed for subsequent tasks.

### Steps to reproduce
For my use case, I added the active ansible user to the `docker` group to use various docker functions.
1. `user: name=vagrant groups=docker append=yes` # this works
1. `meta: reset_connection` # this generates an error but ansible continues
1. attempt to use any `docker_*` module

### Expected result
The connection should reset and the calls to docker related modules should execute successfully.

### Actual result
The connection does not terminate correctly and the docker  modules fail with permission denied errors from the docker daemon.  Upon further testing, I was able to confirm that the ansible user session remains intact and the new docker group is never able to be used.

### Additional details
* The use of the `sg` command for shell and command steps works expected but that cannot be used with defined modules
* The use of `become: yes` + `become_user: "{{ ansible_env.USER }}" does not work but there may be a way to make that work with become_flags
 * `newgrp` cannot be used because it spawns an entirely new session and ansible hangs until the session has terminate, which drops back to the original session

This works but it's pretty hacky:
```
    - command: "pkill -U {{ ansible_env.USER }} sshd"
      ignore_errors: yes 
      ignore_unreachable: yes
```

There is also `meta: clear_host_errors` but that won't work when there's a single host in play.  When ansible hits a condition where all hosts are unreachable, it terminates which means for a single host, it can never reach that point.  The docs don't currently make that clear but this comment does:
https://github.com/ansible/ansible/issues/26362

**Comment by apatard** [comment]
It turns out it's a bug in Ansible ssh connection plugin. As a workaround, you can configure the ``control_path`` ansible option to a custom path (see https://molecule.readthedocs.io/en/latest/configuration.html#provisioner)

**Comment by apatard** [comment]
Unless I'm mistaken, there's nowadays no supported version of ansible with this issue, so I'm closing it.
