### ISSUE TITLE
Molecule login should honor ssh config_options

### ISSUE THREAD

**Issue by anderpups** [ansible-community/molecule-vagrant#134]
I am trying to get the `molecule login` command to pass -X ssh extra_arg. It works when I do a `vagrant ssh` and I can see the option in the Vagrantfile created by Molecule. Would it be possible to have those arguments passed when doing a `molecule login`?
Below is how I am attempting to have that passed. Thanks!
```
platforms:
  - name: builder-oel8
    box: dti_oel8
    cpus: 4
    memory: 16384
    provider_raw_config_args:
      - "nested = true"
      - "machine_virtual_size = 250"
    config_options:
      ssh.extra_args:
        - "-X" # Pass X so we can open vncviewer when we do a molecule login

**Comment by konstruktoid** [comment]
Have you tried https://github.com/ansible-community/molecule-vagrant/blob/main/molecule_vagrant/driver.py#L107-L110?

**Comment by apatard** [comment]
@anderpups molecule login should honor  ``ssh_connection_options`` and it seems to be working here (look at ``login_cmd_template`` in ``molecule_vagrant/driver.py``):
```
driver:
  name: vagrant
  ssh_connection_options:
  - "-X"
```
And after running a ``molecule create`` and ``molecule login``, I can see:
```
$ ps -ef|grep <IP>
...
/bin/sh -c /usr/bin/env ssh <IP> -l vagrant -p 22 -i /path/to/private_key -X
...
```

Did you check with ps as I did that ``ssh_connection_options`` was really not working ? Can you provide more information about your setup so I can try to reproduce ?

**Comment by anderpups** [comment]
@apatard Thank you, I had not tried that.

That only seems to work if you don't gather_facts or don't use any module that uses scp. Otherwise, it tries to add -X to the scp command which doesn't work. Unfortunately in this case I need the ansible_facts so it won't work. Thank you though.

**Comment by apatard** [comment]
I've not tried it, but what about using ``-o ForwardX11=yes`` instead of ``-X`` ?

**Comment by anderpups** [comment]
@apatard  Thank you! That did it! I am going to close this issue.

**Comment by anderpups** [comment]
```
driver:
  name: vagrant
  ssh_connection_options:
    - '-o ForwardX11=yes'
```
fixed the issue
