### ISSUE TITLE
Create boolean option for vm.hostname

### ISSUE THREAD

**Issue by anderpups** [ansible-community/molecule-vagrant#157]
It would be awesome to have a an option to not set the hostname for the Vagrant instance. I am working with f5 vms and they are hanging on '==> localhost: Setting hostname...' 
c
.vm.hostname = "{{ instance.name }}"

**Comment by apatard** [comment]
I have to think how to handle that but it should be possible to implement it. Thing is that while I'm at it, it may be interesting to allow settting the hostname or not and to be able to configure the hostname. Not sure yet what would be the side effect of setting arbitrary host name.

However, could it be possible that it's also an issue with your f5 vagrant box ?

Can you also confirm that removing the hostname configuration makes things work ?

**Comment by anderpups** [comment]
Thank you for your response. The issue with the f5 vagrant box is they run their own OS that doesn't use /etc/hostname or /etc/hosts which Vagrant uses to set the hostname. I added the below code to vagrant.py in molecule_vagrant/modules and it has solved my problem, but there is probably a better way of handling it.

```
 {% if instance.set_hostname is sameas false %}
    c.vm.hostname = "{{ instance.name }}"
 {% endif %}
```

**Comment by apatard** [comment]
oh ok. This made me think that in your case, with newer enough version of vagrant, something like that may work:

```
       config_options:
         vm.allow_hosts_modification: false
```

Please don't close this bug, even if this vagrant setting will solve your use case. This bug is still valid and I want to look at the ``config.vm.hostname`` template to disable setting it to set it to a custom value.

**Comment by anderpups** [comment]
I didn't realize `allow_hosts_modification` was an option. That resolved my issue. Thank you!
