### ISSUE TITLE
Failure to destroy if no box file specified

### ISSUE THREAD

**Issue by Maddog2050** [ansible-community/molecule-vagrant#19]
Hi,

I've found an issue where if you don't specify the box file in your molecule.yml file the VirtualBox vm is not removed/destroyed after it is halted.

A workaround for this would be to set the same default that is in the create.yml.

Regards

Adam

**Comment by apatard** [comment]
Is it possible to get more details please, in order to try reproducing this here ?

**Comment by apatard** [comment]
Is this bug still there ? I think it's solved but I don't want to close a bug without being sure it's really solved.

**Comment by apatard** [comment]
Given that there's no news, I'm going to close this bug, just to clean things. Please reopen the bug if it's still there.
