### ISSUE TITLE
2.0.0 not on pypi.org

### ISSUE THREAD

**Issue by dvzrv** [ansible-community/molecule-vagrant#208]
Hi! I'm packaging this project for Arch Linux.

For 2.0.0 there is no sdist tarball on pypi.org. We usually use it to build the package.

**Comment by dvzrv** [comment]
FWIW, I have switched to the auto-generated github tarball for now, but it requires me to manually set the package version using `SETUPTOOLS_SCM_PRETEND_VERSION` as setuptools-scm can not derive it from that tarball.

**Comment by dvzrv** [comment]
As pointed out in #209 it appears the only way to successfully build the package (with all required files) is by using a git checkout of the repository at this point in time.
Relying on the auto-generated source tarball on github leads to a wheel that does not include all files.

**Comment by ssbarnea** [comment]
v2.0.0 is on pypi now https://pypi.org/project/molecule-vagrant/

PS. Please note that I removed the old tags that were not published in order to be able to re-leases it.
