### ISSUE TITLE
CI needs to be setup

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule-vagrant#3]
AFAIK Vagrant cannot be run on Travis because VM support is disabled by them so another platform will be needed.

As Molecule itself is migrating from Travis to Zuul, it would make sense to try to use the same but the decision should be taken by [maintainers](#2 ).

**Comment by apatard** [comment]
What about using the vagrant docker provider until it's possible to run a VM ? It clearly won't replace a VM and vagrant with molecule is possibly used only to create VMs but it's better than nothing imho.

Possible problem with this idea: I'm not even sure that it's possible to use the vagrant docker provider with molecule 2.x.

_Disclaimer: I've never used the docker provider, I've used so far only the vagrant-libvirt provider._

**Comment by obowersa** [comment]
I've got a few bug fixes in the works for this module, and got some experience with zuul so I'll have a look at testing them locally with that.

Mainly putting this here as a note to myself as I will need to have a chat with my employer about a couple of things.

**Comment by apatard** [comment]
@ssbarnea @obowersa I hope to find time to work on that in next days//weeks, Has any of you pointers how to work on the CI setup ?

**Comment by ssbarnea** [comment]
CI is setup now, but only the fedora-30 job is working, the other ones fail because vagrant-libvirt driver is broken. They are made non-voting, maybe someone figures a way to fix it by tunning https://github.com/ansible-community/molecule-vagrant/blob/master/tools/test-setup.sh

**Comment by apatard** [comment]
@ssbarnea fwiw, I've uploaded on my fork a version of test-setup.sh on Debian Buster (I've not tested inside Zuul for now)

**Comment by ssbarnea** [comment]
We can run Debian/Ubuntu too , we need to update the test jobs to include it too somewhere.

**Comment by apatard** [comment]
I've made a pull request solving the centos 7/8 issues. For Debian/Ubuntu, I'll create a new branch for this as my setup branch is modifying the test-setup.sh script to install pip while I should rather modify the bindep.txt file.
Moreover this file which is wrong anyway for these platforms. For instance, ``build-dep`` doesn't exist but ``build-essential`` does.

**Comment by ssbarnea** [comment]
Already fixed, feel free to make PRs.
