### ISSUE TITLE
please add 'hashicorp' with Manage Topics

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-community/molecule-vagrant#33]
This content is related to @hashicorp please add a topic so we can filter. Also consider inviting Hashicorp employees or Hashicorp ambassadors.

@ksatirli Who should be involved?

**Comment by ssbarnea** [comment]
Done!

**Comment by ksatirli** [comment]
@bbaassssiiee as a recently minted Ambassador, I think you might be the right choice for this!

For things that are an issue in [hashicorp/vagrant](https://github.com/hashicorp/vagrant) directly, that repository's Issues section is the best place to report it.

**Comment by ssbarnea** [comment]
I just invited @bbaassssiiee, I am more than pleased to do it.
