### ISSUE TITLE
config_options is ignored

### ISSUE THREAD

**Issue by richb-ibm** [ansible-community/molecule-vagrant#34]
I was trying to pass a private key path to VirtualBox via vagrant like this:
```yaml
platforms:
  - name: instance
    box: IBM.EI.RHEL.7
    config_options:
      ssh.private_key_path: "'<private key path>'"
```
but `config_options` seems to be ignored.

These are the versions I am running:
```
~ » pip list | grep molecule        
molecule                               3.0.2.1
molecule-vagrant                       0.2
```

I believe I have traced the issue to this [line](https://github.com/ansible-community/molecule-vagrant/blob/4ec068d2f7e8af6c3a9b0f85675c2603fd1211a5/molecule_vagrant/modules/vagrant.py#L565) in vagrant.py:
```python
        molecule.util.merge_dicts(
            d["config"]["options"], self._module.params["config_options"]
        )
```
`molecule.util.merge_dicts` returns a new merged dictionary so that doesn't update `d["config"]["options"]` and so any config options are ignored.

This seems to fix the issue:
```python
        d["config"]["options"] = molecule.util.merge_dicts(
            d["config"]["options"], self._module.params["config_options"]
        )
```

Also, I believe `provider_options` has the same issue and [this code](https://github.com/ansible-community/molecule-vagrant/blob/4ec068d2f7e8af6c3a9b0f85675c2603fd1211a5/molecule_vagrant/modules/vagrant.py#L571) needs the same type of update:
```python
        molecule.util.merge_dicts(
            d["provider"]["options"], self._module.params["provider_options"]
        )
```

Is this a bug or am I missing something?

**Comment by apatard** [comment]
I can't give any time frame but I hope that there will be a 0.3 release soon, which will include the mentionned pull request.

**Comment by apatard** [comment]
@richb-ibm So, soon was now. 0.3 is out. Can you check with 0.3 and close this bug if your issue is fixed ?

**Comment by richb-ibm** [comment]
I tried out 0.3 today and it worked great.  Thank you!
