### ISSUE TITLE
`molecule lint` fails to prevalidate

### ISSUE THREAD

**Issue by meroupatate** [ansible-community/molecule-vagrant#40]
I'm using **molecule 3.0.5** with **molecule-vagrant-0.3**.

My `molecule.yml` file is configured to use molecule-vagrant. However, when I try to run `molecule lint`, it does not recognise the `vagrant` driver.

Here is the error output i get:
```bash
$ molecule lint                             
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: 'set -e

  yamllint .

  ansible-lint

  flake8

  '
platforms:
  - box: ubuntu/bionic64
    name: instance
provisioner:
  name: ansible
verifier:
  name: ansible

ERROR: Failed to pre-validate.

{'driver': [{'name': ['unallowed value vagrant']}]}
```

I think it might be related to this issue: https://github.com/ansible-community/molecule/issues/2560#issue-566151191

**Comment by apatard** [comment]
Weird. Are you sure that molecule-vagrant is installed correctly ?
Can you please check with:
```shell
$ pip3 list | grep molecule
molecule           3.0.5         
molecule-vagrant   0.3           
$ python3
>>> from molecule import api
>>> api.drivers()
[delegated, docker, podman, vagrant]
>>> 
```

**Comment by meroupatate** [comment]
Yeah i get the same output:
```bash
$ pip3 list | grep molecule
molecule          3.0.5    
molecule-vagrant  0.3      

$ python3
Python 3.8.3 (default, Jul  8 2020, 14:27:55) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from molecule import api
>>> api.drivers()
[delegated, docker, podman, vagrant]
>>> 
```

**Comment by meroupatate** [comment]
Oh actually you were right, something was messed up with my local python installation, for some reason molecule was using a different version of python than the one linked to `pip3` and `python3`.
It works fine now sorry about that
