### ISSUE TITLE
identify and use the smallest possible libvirt enabled box

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule-vagrant#48]
Currently we use "generic/alpine310" box which is just above 100MB but it we can find an even smaller one we can speed-up testing even more. See https://app.vagrantup.com/generic/boxes/alpine310

The only requirement is to be able to boot the VM to validate that molecule/ansible can connect to it, nothing more.

**Comment by apatard** [comment]
Actually, we're also using the ``centos/7`` box which is possibly bigger. I don't remember why we're not using the alpine one for the tests. Please also note that boxes are downloaded only one time. If the box is already added to vagrant, it's not downloaded again.

**Comment by ssbarnea** [comment]
We need to be sure to use only one image and a minimal one, because on CI/CD we have no caching and they are downloaded each time.

**Comment by apatard** [comment]
yeah, I know. I'm using locally fresh vagrant box to run the test inside them, so no cache too. Increasing the testsuite speed is on my TODO. I've switched ``gathering`` to ``explicit`` which allows to gain few secs, I've yet to check if ``pipelining`` will help too and of course, this problem of box images to download is on the same todo.
Too bad that there's no cirros box for vagrant, there's usually very small.
btw, if we change the box to use while testing, it may be interesting to change the default box to use, which is this alpine box. wdyt ?

**Comment by apatard** [comment]
More thoughts about the subject: it should be minimal and be coming with python. The alpine image is about 100M and according to the test logs:
```
        (1/4) Installing libbz2 (1.0.6-r7)
        (2/4) Installing expat (2.2.8-r0)
        (3/4) Installing gdbm (1.13-r1)
        (4/4) Installing python3 (3.7.7-r1)
        Executing busybox-1.30.1-r4.trigger
        OK: 205 MiB in 88 packages
```
So, in the end, we've downloaded about 300M, which is about the size of centos/fedora/debian images (which have python).
Moreover, this may also mean that every test will install python3 in the new VM, so each time download 200M. Maybe vagrant-cachier would work (no idea, never used) but not relying on extra vagrant plugin would be better.

**Comment by apatard** [comment]
hm. I think I may have misread the logs, but still, would be nice to avoid downloading again and again python.

**Comment by apatard** [comment]
I've done some work to use the alpine/generic310 box for all tests. In order to avoid downloading python3 and rsync everything, I've modified the test-setup script to create a new box out of the freshly booted one and use the provisionning to install python3 and rsync in it.
It did improve things, even if I expected more gain.
I'll send a PR after having the tweaks and new qemu fallback PR merged (the last one has not yet been sent)

**Comment by ssbarnea** [comment]
We do not really need to install anything on the booted machine. Ansible can manage hosts that do not have python installed on them. We only need to assure we only call `raw` module during testing as modules like `command`, `shell` or `setup` do require python.

**Comment by apatard** [comment]
@ssbarnea is this bug still valid ? I guess PR62 kind of solved this issue. If not, please, can you tell me what's missing so that I can work on it ?

**Comment by ssbarnea** [comment]
I will close it for now with the remark that if someone propose a PR that reduces the image size even further, I would not mind accepting it.
