### ISSUE TITLE
Intermittent failure with create.yml due to 'NoneType' object has no attribute 'splitlines' when getting ssh_config

### ISSUE THREAD

**Issue by amartin3225** [ansible-community/molecule-vagrant#66]
I am calling molecule-vagrant from jenkins to test running playbooks inside vagrant VMs; I am using the following versions:

- molecule-vagrant==0.3
- molecule==3.0.8
- python-vagrant=0.5.15

Intermittently, the [Create molecule instance(s)](https://github.com/ansible-community/molecule-vagrant/blame/master/molecule_vagrant/playbooks/create.yml) step fails with the following error:

```
Traceback (most recent call last):
  File "/home/docker/.ansible/tmp/ansible-tmp-1603322645.5232747-66-255606826057086/AnsiballZ_vagrant.py", line 102, in <module>
  _ansiballz_main()n  File "/home/docker/.ansible/tmp/ansible-tmp-1603322645.5232747-66-255606826057086/AnsiballZ_vagrant.py", line 94, in _ansiballz_main
  invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/docker/.ansible/tmp/ansible-tmp-1603322645.5232747-66-255606826057086/AnsiballZ_vagrant.py", line 40, in invoke_module
  runpy.run_module(mod_name='ansible.modules.vagrant', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
  return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
  mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
  exec(code, run_globals)
  File "/tmp/ansible_vagrant_payload_pa1lhbef/ansible_vagrant_payload.zip/ansible/modules/vagrant.py", line 632, in <module>
  File "/tmp/ansible_vagrant_payload_pa1lhbef/ansible_vagrant_payload.zip/ansible/modules/vagrant.py", line 620, in main
  File "/tmp/ansible_vagrant_payload_pa1lhbef/ansible_vagrant_payload.zip/ansible/modules/vagrant.py", line 451, in up
  File "/tmp/ansible_vagrant_payload_pa1lhbef/ansible_vagrant_payload.zip/ansible/modules/vagrant.py", line 480, in _conf
  File "/tmp/python/lib/python3.6/site-packages/vagrant/__init__.py", line 540, in conf
  conf = self._parse_config(ssh_config)
  File "/tmp/python/lib/python3.6/site-packages/vagrant/__init__.py", line 931, in _parse_config
  for line in ssh_config.splitlines():
  AttributeError: 'NoneType' object has no attribute 'splitlines'
```

This appears to be generated by [this line](https://github.com/todddeluca/python-vagrant/blob/master/vagrant/__init__.py#L931) if `vagrant ssh-config` does not return the SSH config. 

If this is an intermittent problem with vagrant (as the [note in create.yml](https://github.com/ansible-community/molecule-vagrant/blob/master/molecule_vagrant/playbooks/create.yml#L36) suggests), would it make sense to [retry this task a few times](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#retrying-a-task-until-a-condition-is-met) so this failure doesn't occur? Or, is there another way to fix this intermittent failure?

Thanks!

**Comment by apatard** [comment]
When this error is happening, did you look at the files in ``~/.cache/molecule/$role/$scenario/`` ? (mainly the ``.err`` and ``.out`` files but the other may give clues about the issue).
Looking at look ``vagrant global-status`` may help too.

btw:
- are you using a scenario with multiple VMs ?
- which provider ? virtualbox ? libvirt ?

**Comment by amartin3225** [comment]
I'll try to add code to capture the `.err` and `.out` files as well as `vagrant global-status` and let you know what I find.

> are you using a scenario with multiple VMs ?

The scenario only involves a single VM, but Jenkins is running multiple scenarios (each with their own VM) concurrently

> which provider ? virtualbox ? libvirt ?

libvirt

**Comment by apatard** [comment]
> I'll try to add code to capture the `.err` and `.out` files as well as `vagrant global-status` and let you know what I find.
> 
> > are you using a scenario with multiple VMs ?
> 
> The scenario only involves a single VM, but Jenkins is running multiple scenarios (each with their own VM) concurrently

So, single VM. How interesting. I hope this would make easier to find a way to reproduce here and generate a test case from it. If there's nothing secret, can you also share your molecule.yml file please ?

**Comment by amartin3225** [comment]
I was able to capture the `.out` and `.err` files:

Here's the end of `.out`:

```
hostname: Starting domain.
hostname: Waiting for domain to get an IP address...
hostname: Waiting for SSH to become available...
hostname: 
hostname: Vagrant insecure key detected. Vagrant will automatically replace
hostname: this with a newly generated keypair for better security.
hostname: 
hostname: Inserting generated public key within guest...
hostname: Removing insecure key from the guest if it's present...
hostname: Key inserted! Disconnecting and reconnecting using new SSH key...
hostname: Setting hostname...
hostname: Machine not provisioned because `--no-provision` is specified.
```

Here's the `.err` contents:

```
The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.
```

And here's what `vagrant global-status` shows during this time:

```
id       name                                                      provider state   directory                                                                    
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
0e58227  hostname libvirt running /tmp/molecule/hostname 
 
The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date (use "vagrant global-status --prune" to prune invalid
entries). To interact with any of the machines, you can go to that
directory and run Vagrant, or you can use the ID directly with
Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
```

So it seems like SSH isn't starting properly inside the vagrant VM. For reference, this is an Ubuntu 16.04 VM. Which part of the `molecule.yml` do you want to see (mine is quite long so I can pull out the relevant section)?

**Comment by apatard** [comment]
Did you try to login inside the VM and check if it got an IP ?

I was asking the ``molecule.yml`` file in order to try reproducing here (or at least parts of it).
It was also to check different things, for instance network configuration. Some distributions are using
``qemu:///session`` by default and it tends to break the network. Seems like I forgot to ask the distribution you're using, btw.

**Comment by amartin3225** [comment]
Is there a way that I can login inside the VM to check the IP without an interactive session (e.g. from a script)? Jenkins is running these VMs so I cannot interact directly with them. I am not able to readily reproduce this error if running a single VM directly - this intermittent issue seems to only manifest on a handful of VMs when Jenkins is running 100+ of these during a build (note that it only builds a small number of VMs concurrently though). The guest OS is Ubuntu 16.04 and the host OS is Ubuntu 18.04.

**Comment by apatard** [comment]
I was about suggesting to use ``virsh console`` but it's a bad idea. If you're using dhcp, maybe looking at virsh net-dhcp-leases for the involved network will help.

There's also a possibility: you're running into one form of the issues with network and vagrant-libvirt failing to catch the network IP, and that the ``vagrant.py`` module is not able to catch the error properly.
Can you also try with different network adapter, ``e1000`` instead of ``virtio`` for instance ?

**Comment by amartin3225** [comment]
I think I've isolated the problem after adding additional debugging commands immediately after [Create molecule instance(s)](https://github.com/ansible-community/molecule-vagrant/blame/master/molecule_vagrant/playbooks/create.yml) fails:
```
17:46:23 + vagrant global-status
17:46:25 id       name                                                     provider state   directory                                                                 
17:46:25 -------------------------------------------------------------------------------------------------------------
17:46:25 d34e9fc  test-vagrant                                             libvirt running /tmp/molecule/test-vagrant 
17:46:30 + vagrant ssh-config d34e9fc
17:46:37 The provider for this Vagrant-managed machine is reporting that it
17:46:37 is not yet ready for SSH. Depending on your provider this can carry
17:46:37 different meanings. Make sure your machine is created and running and
17:46:37 try again. Additionally, check the output of `vagrant status` to verify
17:46:37 that the machine is in the state that you expect. If you continue to
17:46:37 get this error message, please view the documentation for the provider
17:46:37 you're using.
17:46:37 # running other debug commands for awhile...
17:47:20 + vagrant ssh-config d34e9fc
17:47:23 Host test-vagrant
17:47:23   HostName 192.168.100.112
17:47:23   User vagrant
17:47:23   Port 22
17:47:23   UserKnownHostsFile /dev/null
17:47:23   StrictHostKeyChecking no
17:47:23   PasswordAuthentication no
17:47:23   IdentityFile /tmp/molecule/test-vagrant/.vagrant/machines/test-vagrant/libvirt/private_key
17:47:23   IdentitiesOnly yes
17:47:23   LogLevel FATAL
```

Based on this, it looks like the problem is that `Create molecule instance(s)` is not waiting long enough for the VM to actually come up and be ready; if it could sleep or wait for another minute or two, then the VM would be in a usable state and `vagrant ssh-config` would return successfully. Is it possible to add a delay or sleep so that vagrant has enough time to finish initializing?

**Comment by apatard** [comment]
The code is only waiting for the return of ```vagrant up```. No timeout at all since this command is handling it: it's ending either by failing to bring the VM up, possibly after an internal timeout, or when the VM is up.

From what you've provided, for unknown reasons, vagrant-libvirt is waiting for the VM/SSH to be up and fails. Eventually, after quite some time, vagrant-libvirt is finally reporting the SSH is available. Maybe your ubuntu VM is taking a lot of time to start the SSH ? Can't it be something related to your test environment, like overloaded box or libvirt using tcg instead of kvm ? At least, I begin to think that it doesn't seem to be an issue with molecule-vagrant per itself.

If I understand vagrant-libvirt correctly:
- the wait for the domain to be up is hardcoded to 10min (https://github.com/vagrant-libvirt/vagrant-libvirt/blob/f51192e80b3a9d671da7948c8d2d92b4c89d29f2/lib/vagrant-libvirt/action/wait_till_up.rb#L39)
- the SSH timeout is hardcoded to 2 mins (https://github.com/vagrant-libvirt/vagrant-libvirt/blob/f51192e80b3a9d671da7948c8d2d92b4c89d29f2/lib/vagrant-libvirt/action/wait_till_up.rb#L72)
It's quite long time.

So, on molecule-vagrant, I fear that there are not a lot of things to do. You may try by adding retries+delay to https://github.com/ansible-community/molecule-vagrant/blob/07f205be6194aadcecfc91515d697eaf15b4349e/molecule_vagrant/playbooks/create.yml#L8 but I don't know how vagrant will react if ```vagrant up``` is called several time.

**Comment by amartin3225** [comment]
Thanks for explaining how the timeouts in the dependent code works. Looking more closely, the 3 failures I saw recently all have the following timestamps:
```
17:42:57     TASK [Create molecule instance(s)] *********************************************
17:46:22     An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'splitlines'
17:47:12 + vagrant ssh d34e9fc -- sudo ip a # succeeded
# wait 4:15 until SSH is up

17:43:13     TASK [Create molecule instance(s)] *********************************************
17:46:22     An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'splitlines'
17:47:12 + vagrant ssh 097b239 -- sudo ip a # succeeded
# wait 3:59 until SSH is up

18:13:59     TASK [Create molecule instance(s)] *********************************************
18:16:06     An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'splitlines'
18:16:15 + vagrant ssh-config 2a04227 # succeeded
# wait: 2:16 until SSH is up
```

So each failure occurs in around 2-3 minutes from when the task starts, which seems more likely to be the SSH timeout since it is not even close to the 10 minute timeout waiting for the domain to be up. I do not see evidence of resource contention on the host, so while these values are somewhat slow, there isn't an obvious cause. I'll see if I can re-run with the [SSH timeout](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/f51192e80b3a9d671da7948c8d2d92b4c89d29f2/lib/vagrant-libvirt/action/wait_till_up.rb#L72) set to a larger value and see if that helps.

**Comment by amartin3225** [comment]
Hm... even with this change:
```diff
diff --git a/lib/vagrant-libvirt/action/wait_till_up.rb b/lib/vagrant-libvirt/action/wait_till_up.rb
index 30a9413..980e19e 100644
--- a/lib/vagrant-libvirt/action/wait_till_up.rb
+++ b/lib/vagrant-libvirt/action/wait_till_up.rb
@@ -71,7 +71,7 @@ module VagrantPlugins
           # connect via ssh.
           env[:metrics]['instance_ssh_time'] = Util::Timer.time do
             env[:ui].info(I18n.t('vagrant_libvirt.waiting_for_ssh'))
-            retryable(on: Fog::Errors::TimeoutError, tries: 60) do
+            retryable(on: Fog::Errors::TimeoutError, tries: 300) do
               # If we're interrupted don't worry about waiting
               next if env[:interrupted]
```

I still saw the same type of failure with the same time period of around 2-3 minutes:
```
18:15:03     TASK [Create molecule instance(s)] *********************************************
18:17:45     An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'splitlines'
18:17:51 + vagrant ssh-config 28b71a8 # this worked
```

This makes me think it cannot be anything to do with either of these timeouts since now both of them are 10 minutes and this failure occurred well before that. I was able to review dmesg and the syslog for the vagrant VM and can see that the entire boot takes a little over 1 minute:
```
Dec  9 00:16:07 vagrant kernel: [    0.000000] Initializing cgroup subsys cpuset
...
Dec  9 00:16:07 vagrant kernel: [   27.921835] EXT4-fs (vda1): re-mounted. Opts: errors=remount-ro
...
Dec  9 00:16:08 vagrant dhclient[495]: DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 3 (xid=0x2dc44606)
...
Dec  9 00:16:11 vagrant dhclient[495]: DHCPACK of 192.168.100.219 from 192.168.100.1
Dec  9 00:16:52 vagrant dhclient[495]: bound to 192.168.100.219 -- renewal in 1381 seconds.
...
Dec  9 00:16:52 vagrant systemd[1]: Reached target Network.
Dec  9 00:16:52 vagrant systemd[1]: Starting OpenBSD Secure Shell server...
Dec  9 00:16:52 vagrant systemd[1]: Reached target Network is Online.
...
Dec  9 00:16:55 vagrant systemd[1]: Startup finished in 27.266s (kernel) + 48.896s (userspace) = 1min 16.163s.
```

Does this boot time seem particularly long such that it would be the source of this problem?

**Comment by apatard** [comment]
more than 2mins sounds quite a lot. Maybe you could ask for some advice/help to vagrant-libvirt developers ?

**Comment by amartin3225** [comment]
Okay, I will check with them. Thank you for the help.

**Comment by apatard** [comment]
@amartin3225 did you manage to solve the timeout issue ? Can this bug be closed ?

**Comment by amartin3225** [comment]
I found that the issue was with the version of `python-vagrant` that `molecule-vagrant` uses. Since `python-vagrant` appears to be no longer maintained, I made a fork of it with this patch which seems to resolve the problem for me:

```diff
@@ -19,6 +19,7 @@
 import subprocess
 import sys
 import logging
+import time

 # local
 from . import compat
@@ -537,6 +538,14 @@
         if self._cached_conf.get(vm_name) is None or ssh_config is not None:
             if ssh_config is None:
                 ssh_config = self.ssh_config(vm_name=vm_name)
+                if ssh_config is None:
+                    tries = 0
+                    while tries <= 20:
+                        ssh_config = self.ssh_config(vm_name=vm_name)
+                        if ssh_config:
+                            break
+                        i+=1
+                        time.sleep(30)
             conf = self._parse_config(ssh_config)
             self._cached_conf[vm_name] = conf
```

I think this issue can be closed since the problem isn't in `molecule-vagrant` itself

**Comment by apatard** [comment]
@amartin3225 Ok. Thanks for the feedback. I'll close the bug then. Please note that @konstruktoid has created a fork so he may be interesting in this change. I don't know the exact status of this fork, if it's ready for use or not.

**Comment by konstruktoid** [comment]
Hi @amartin3225, the fork is available at https://github.com/konstruktoid/python3-vagrant and I'm not going to say it ready or not, only that I use it as a python-vagrant replacement without any issues.

I believe I've applied most patches and merged most PRs from the original project, and updated it to Python3 and adapted to the Black code formatter among other things.

**Comment by amartin3225** [comment]
Sounds good, thanks for letting me know!
