### ISSUE TITLE
v0.4 not available from PyPI

### ISSUE THREAD

**Issue by sio** [ansible-community/molecule-vagrant#71]
According to the releases page [v0.4](https://github.com/ansible-community/molecule-vagrant/releases/tag/0.4) has been published last week, but it was never uploaded to PyPI. Is there some specific reason for that?

**Comment by apatard** [comment]
There were some bugs in the release script, preventing the 0.4 upload to pypi, @ssbarnea has fixed that and released 0.5 on pypi (in order to get compatibility with molecule 3.2), so I'm closing this bug.
