### ISSUE TITLE
Latest release depends on an alpha version of molecule

### ISSUE THREAD

**Issue by bendem** [ansible-community/molecule-vagrant#82]
I'm trying to install `molecule-vagrant` using pipenv and the graph cannot be resolved:

```
There are incompatible versions in the resolved dependencies:
  molecule[docker,lint]==3.1.5 (from -r /tmp/pipenv0kzmaqemrequirements/pipenv-e55zl6g7-constraints.txt (line 5))
  molecule>=3.2.0a0 (from molecule-vagrant==0.5->-r /tmp/pipenv0kzmaqemrequirements/pipenv-e55zl6g7-constraints.txt (line 2))
```

[This change](https://github.com/ansible-community/molecule-vagrant/pull/72/files#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R66) makes molecule-vagrant require an alpha version of molecule. Does that mean that molecule-vagrant is not compatible with any released version of molecule? If so, can the required version be updated to be the minimum version and not the maximum version? Could also be `>=3.0.2,<3.3` if you don't want to support newer versions by default.

**Comment by bendem** [comment]
It also looks like the previous release (0.4) was not pushed to pypi.org, preventing me to use that as well.

**Comment by sio** [comment]
If I recall correctly, each of previous molecule-vagrant releases will be
broken with current stable molecule. See #43

So yeah, you need to either pin molecule to an alpha version and use
molecule-vagrant 0.5, or pin molecule-vagrant to 0.3 and use older molecule
version, probably <3.1

Things should come back to normal after molecule 3.2 release.

**Comment by apatard** [comment]
There was a bug in our release script and they broke when the 0.4 release was done, preventing the upload.
If you want 0.4, with pip, it's possible to install it, by asking pip to use git:
```
pip install git+https://github.com/ansible-community/molecule-vagrant.git@0.4
```
as said @sio, hopefully, this issue will be solve with 3.2 release.

**Comment by bendem** [comment]
Alright, it looks like the whole molecule dependency graph is broken until molecule 3.2, I'll close this.
