### ISSUE TITLE
Kill vagrant.yml

### ISSUE THREAD

**Issue by apatard** [ansible-community/molecule-vagrant#86]
Using a vagrant.yml file to store the instance information is making things a little bit more complicated than necessary. The Vagrantfile is reading the vagrant.yml file to configure the VM when vagrant up is called, so extra overhead compared to having the Vagrantfile having the VM configuration already set.
This is also possibly the reason for the weird syntax for some configuration value, like:
```
  - name: instance
    provider_options:
      nic_model_type: '"e1000"'
```

The last (subjective) reason is that I find it makes debugging things a little bit more complicated.

Possible and expected/wanted side-effects:
- this will make this easier to enable proper multi platform support.
- the current Vagrantfile is limiting the number of possible providers, which means that things are not working for users of providers not handled by it.

**Note**: I've already some code for that, loosely based on what was PR31. A draft PR will be opened soon I hope

**Comment by ssbarnea** [comment]
Correct me if I am wrong: that propose to directly template a Vagrantfile using Ansible template module and avoid the need to use an intermediary vagrant.yml file?

If true, I am for it as it removes a layer that makes it quite hard to debug, update or extend.

The big question here will be how complex the templating will become, can we master this amount of jinja? The main concern is that we not want to force users to create local Vagrant files, at least not for most of them.

**Comment by apatard** [comment]
@ssbarnea yes, to summarize the idea is to generate only the Vagrantfile, with the help of jinja2. See my PR. It's a PR draft for now, since (at least) I'm unable to run the full CI on it due to bad internet connection.
